apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aws-eks-backend
  namespace: monitoring
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: aws-eks-backend

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
